version: '3.8'
services:
  eureka-server:
    image: smartassurance-eureka-server:0.0.1-SNAPSHOT
    build: eureka-server/
    ports:
      - 8761:8761
  gateway:
    image: smartassurance-gateway:0.0.1-SNAPSHOT
    build: gateway/
    depends_on:
      - eureka-server
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
    ports:
      - 8082:8082